# {{- $kcSecretName := printf "%s-%s" (include "ches.fullname" .) "keycloak" }}
# {{- $kcSecret := (lookup "v1" "Secret" .Release.Namespace $kcSecretName ) }}

# {{- if not $kcSecret }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   {{- if not .Values.config.releaseScoped }}
#   annotations:
#     "helm.sh/resource-policy": keep
#   {{- end }}
#   name: {{ $kcSecretName }}
#   labels: {{ include "ches.labels" . | nindent 4 }}
# type: kubernetes.io/basic-auth
# data:
#   password: {{ .Values.keycloakSecretOverride.password | b64enc | quote }}
#   username: {{ .Values.keycloakSecretOverride.username | b64enc | quote }}
# {{- end }}
