---
apiVersion: v1
kind: Template
labels:
  template: "${REPO_NAME}-template"
  app: "${APP_NAME}-${JOB_NAME}"
metadata:
  name: "${REPO_NAME}-redis-dc"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${APP_NAME}-redis-${JOB_NAME}"
  spec:
    replicas: 1
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-redis-${JOB_NAME}"
    strategy:
      resources: {}
      type: Rolling
    template:
      metadata:
        labels:
          app: "${APP_NAME}-${JOB_NAME}"
          deploymentconfig: "${APP_NAME}-redis-${JOB_NAME}"
      spec:
        containers:
        - image: docker-registry.default.svc:5000/openshift/redis:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6379
            timeoutSeconds: 1
          name: "${APP_NAME}-redis-${JOB_NAME}"
          ports:
          - containerPort: 6379
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - test "$(redis-cli -h 127.0.0.1 -a $REDIS_PASSWORD ping)" == "PONG"
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - mountPath: "/var/lib/redis/data"
            name: redis-${JOB_NAME}-data
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: redis-${JOB_NAME}-secret
        volumes:
        - emptyDir: {}
          name: redis-${JOB_NAME}-data
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}-redis-${JOB_NAME}"
        from:
          kind: ImageStreamTag
          name: redis:latest
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: "${APP_NAME}-redis-${JOB_NAME}"
  spec:
    ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: "${APP_NAME}-${JOB_NAME}"
      deploymentconfig: "${APP_NAME}-redis-${JOB_NAME}"
parameters:
- name: REPO_NAME
  description: Application repository name
  displayName: Repository Name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  displayName: Job Branch Name
  required: true
- name: APP_NAME
  description: Application name
  displayName: Application name
  required: true
