---
apiVersion: v1
kind: Template
labels:
  template: "${REPO_NAME}-template"
  app: "${APP_NAME}-${JOB_NAME}"
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: "redis-${JOB_NAME}-secret"
  stringData:
    password: "${REDIS_PASSWORD}"
parameters:
- name: REPO_NAME
  description: Application repository name
  displayName: Repository Name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  displayName: Job Branch Name
  required: true
- name: APP_NAME
  description: Application name
  displayName: Application name
  required: true
- name: REDIS_PASSWORD
  description: Password of the application database
  displayName: Application Database Password
  generate: expression
  from: "[a-zA-Z0-9]{32}"
  required: true
